import Modals from "@/components/modals";
import Header from "../components/Header";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Theme from "@/components/Theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-100 dark:bg-slate-700">
        <Header />
        <Modals />
        <Toaster reverseOrder={true} />
        <Theme />
        <main className="container mx-auto px-2 py-8">{children}</main>
      </body>
    </html>
  );
}
